version: $(appveyor_repo_tag_name).{build}
image: Visual Studio 2019
configuration: Release
platform:
- Win32
- x64
shallow_clone: true

before_build:
- cmd: >-
    build\beforebuild.bat

build:
  project: bld-vs2015\EngineToolset_vs2015.sln
  verbosity: minimal

after_build:
- cmd: >-
    build\afterbuild.bat

artifacts:
- path: .\dist\xray_re-tools_$(appveyor_repo_tag_name)_$(cor_plat).7z
  name: release

deploy:
- provider: GitHub
  auth_token:
    secure: xjiHaJEbgtHZ9AplJeGwGzPwrLxbYrv+6knxrOBTVevgiI9KWc4pkEAaI/14wJg6
  artifact: release
  on:
    appveyor_repo_tag: true